language: cpp
os:
  - linux
  - osx
compiler:
  - gcc
  - clang
script: mkdir build && cd build && cmake .. && make
dist: trusty
sudo: false
addons:
  apt:
    packages:
    - cmake
    - libgtk2.0-dev
    - libgconf2-dev
    - libgstreamer1.0-dev
