language: cpp
cache:
  directories:
    - $HOME/Library/Caches/Homebrew
os:
  - linux
  - osx
compiler:
  - gcc
  - clang
script:
  - [ "$TRAVIS_OS_NAME" != osx ] || { mkdir build && cd build && cmake .. && make; }
  - [ "$TRAVIS_OS_NAME" != linux ] || docker run -t -v `pwd`:/ws ubuntu:16.04 /ws/scripts/build_in_docker_ubuntu1604.sh
dist: trusty
sudo: false
install:
  - '[ "$TRAVIS_OS_NAME" != osx ] || brew update'
  - '[ "$TRAVIS_OS_NAME" != osx ] || brew install gettext gtk+ jsoncpp'
